services:
  - type: web
    name: naturacorp
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: NaturaCorp
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: false
        # Mettre la vraie valeur manuellement dans le dashboard Render
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: naturacorp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: naturacorp-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: naturacorp-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: naturacorp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: naturacorp-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_LEVEL
        value: error

databases:
  - name: naturacorp-db
    plan: free
